import Sidebar from "@/components/Sidebar/page";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="md:flex ">
          <Sidebar />
          <div className="md:w-3/5 xl:w-4/5 p-6">{children}</div>
        </div>
      </body>
    </html>
  );
}
